execute pathogen#infect()
syntax on
set termguicolors
set expandtab
set tabstop=2 softtabstop=2
set shiftwidth=2
set autoindent
set smartindent
set nu
set relativenumber
set nowrap
set incsearch
set visualbell
set t_vb=
set cursorline
let c_no_curly_error=1
let g:gruvbox_contrast_dark='hard'
let g:gruvbox_contrast_light='soft'
let g:gruvbox_invert_selection=0
autocmd vimenter * ++nested colorscheme gruvbox
if(strftime('%H') >= '18'|| strftime('%H') < 6)
  let g:indentLine_color_gui='#fbf1c7'
  set bg=dark
else
  let g:indentLine_color_gui='#282828'
  set bg=light
endif
function Flip()
  if(&bg == 'dark')
    let g:indentLine_color_gui='#282828'
    set bg=light
  else
    let g:indentLine_color_gui='#fbf1c7'
    set bg=dark
  endif
endfunction
nmap <C-c> <Nop>
nmap <C-f> :call Flip() <CR>
nmap <C-x> :r!cat 
nmap <C-a><C-c> :w <bar> !cat % <bar> clip.exe <CR> <CR>
